Test getCompleteUsersHandler
GET http://localhost:3000/api/users/complete
Content-Type: application/json

Test getPendingUsersHandler
GET http://localhost:3000/api/users/pending
Content-Type: application/json